import type { MapId, VisualCell } from "../shared/types";
import { GLYPH } from "./glyphs";

const tileVisuals: Record<string, VisualCell> = {
	"#": { glyph: GLYPH.brick, className: "tile-brick-emoji" },
	",": { glyph: "", className: "tile-grass" },
	":": { glyph: "", className: "tile-sand" },
	";": { glyph: "", className: "tile-soil" },
	"=": { glyph: "", className: "tile-path" },
	")": { glyph: "", className: "tile-cave-path" },
	".": { glyph: "", className: "tile-floor" },
	"~": { glyph: "", className: "tile-water" },
	"\u0192": { glyph: "", className: "tile-aquarium-fresh-water" },
	"\u00A2": { glyph: "", className: "tile-aquarium-salt-water" },
	"\u00A4": { glyph: "", className: "tile-aquarium-cave-water" },
	"\u00C0": {
		glyph: "o",
		className: "tile-aquarium-fresh-water tile-aquarium-bubble",
	},
	"\u00C1": {
		glyph: "o",
		className: "tile-aquarium-salt-water tile-aquarium-bubble",
	},
	"\u00C2": {
		glyph: "o",
		className: "tile-aquarium-cave-water tile-aquarium-bubble",
	},
	"\u00C4": { glyph: GLYPH.anchor, className: "tile-aquarium-salt-water" },
	"\u00C5": { glyph: GLYPH.rock, className: "tile-aquarium-cave-water" },
	"\u00C6": { glyph: GLYPH.wood, className: "tile-aquarium-fresh-water" },
	"\u00B1": { glyph: "", className: "tile-sand" },
	"\u00B5": { glyph: "", className: "tile-sand" },
	_: { glyph: "", className: "tile-gravel" },
	"^": { glyph: "", className: "tile-forest-grass" },
	"<": { glyph: "", className: "tile-cave-wall-dark" },
	">": { glyph: "", className: "tile-cave-wall-mid" },
	"*": { glyph: "", className: "tile-cave-wall-light" },
	"/": { glyph: GLYPH.ladder, className: "tile-path" },
	T: { glyph: GLYPH.treePine },
	G: { glyph: GLYPH.treeDeciduous },
	C: { glyph: GLYPH.cactus },
	L: { glyph: GLYPH.wood },
	O: { glyph: GLYPH.rock },
	J: { glyph: GLYPH.weed },
	X: { glyph: GLYPH.gift },
	M: { glyph: GLYPH.bottle, className: "tile-sand" },
	S: { glyph: GLYPH.shell, className: "tile-sand" },
	"0": { glyph: GLYPH.wink },
	"6": { glyph: GLYPH.box, className: "tile-grass" },
	"4": { glyph: GLYPH.ninja },
	"5": { glyph: GLYPH.box },
	"7": { glyph: GLYPH.helicopter },
	"8": { glyph: GLYPH.standingMan },
	"9": { glyph: GLYPH.redHeart },
	Z: { glyph: GLYPH.doctor, className: "tile-grass" },
	"{": { glyph: GLYPH.tractor },
	"}": { glyph: GLYPH.tractor },
	"@": { glyph: GLYPH.cat },
	"%": { glyph: GLYPH.blackCat },
	"&": { glyph: GLYPH.dog },
	"?": { glyph: GLYPH.poodle },
	K: { glyph: GLYPH.coral },
	e: { glyph: GLYPH.bear },
	y: { glyph: GLYPH.snake },
	"!": { glyph: GLYPH.poo },
	"+": { glyph: GLYPH.door },
	d: { glyph: GLYPH.bed },
	w: { glyph: GLYPH.tshirt },
	U: { glyph: GLYPH.bath },
	V: { glyph: GLYPH.personBathing },
	j: { glyph: GLYPH.smile },
	l: { glyph: GLYPH.window },
	'"': { glyph: GLYPH.window, className: "tile-roof-white" },
	"\u00A7": { glyph: "", className: "tile-aquarium-roof-b" },
	x: { glyph: GLYPH.brownSquare },
	h: { glyph: GLYPH.chair },
	B: { glyph: "", className: "tile-barn-wall" },
	H: { glyph: GLYPH.brick, className: "tile-brick-emoji" },
	Y: { glyph: GLYPH.seedling },
	i: { glyph: GLYPH.weed },
	"'": { glyph: "'" },
	s: { glyph: GLYPH.seedling, className: "tile-shop-sign" },
	f: { glyph: GLYPH.basket, className: "tile-shop-sign" },
	a: { glyph: GLYPH.cow, className: "tile-shop-sign" },
	$: { glyph: GLYPH.moneyBag, className: "tile-shop-sign" },
	t: { glyph: GLYPH.toolbox, className: "tile-shop-sign" },
	c: { glyph: GLYPH.tshirt, className: "tile-shop-sign" },
	k: { glyph: GLYPH.coffee, className: "tile-shop-sign" },
	n: { glyph: GLYPH.smile },
	b: { glyph: GLYPH.worker, className: "tile-floor" },
	m: { glyph: GLYPH.sunglasses },
	o: { glyph: GLYPH.disguise },
	p: { glyph: GLYPH.cowboy },
	q: { glyph: GLYPH.sailboat },
	r: { glyph: GLYPH.canoe },
	u: { glyph: GLYPH.speedboat },
	v: { glyph: GLYPH.motorboat },
	z: { glyph: GLYPH.rowboatWoman },
	"[": { glyph: GLYPH.fountain, className: "tile-grass" },
	"]": { glyph: GLYPH.palm, className: "tile-grass" },
	"`": { glyph: GLYPH.bat },
	"\\": { glyph: GLYPH.envelope },
	"|": { glyph: GLYPH.fire },
	P: { glyph: GLYPH.satelliteAntenna },
	"1": { glyph: GLYPH.cow },
	"2": { glyph: GLYPH.sheep },
	"3": { glyph: GLYPH.chicken },
	A: { glyph: GLYPH.hippo },
	D: { glyph: GLYPH.unicorn },
	F: { glyph: GLYPH.mammoth },
	I: { glyph: GLYPH.snail },
	N: { glyph: GLYPH.gorilla },
	E: { glyph: GLYPH.egg },
	R: { glyph: "", className: "tile-roof-blue" },
	W: { glyph: "", className: "tile-roof-white" },
	g: { glyph: "", className: "tile-roof-gray" },
	Q: { glyph: "", className: "tile-roof-red" },
	"(": { glyph: GLYPH.tropicalFish, className: "tile-roof-white" },
	"-": { glyph: GLYPH.merwoman, className: "tile-roof-white" },
};

const groundClassByTile: Partial<Record<string, string>> = {
	",": "tile-grass",
	":": "tile-sand",
	";": "tile-soil-dry",
	"=": "tile-path",
	")": "tile-cave-path",
	_: "tile-gravel",
	".": "tile-floor",
	U: "tile-floor",
	x: "tile-floor",
	j: "tile-floor",
	h: "tile-floor",
	"~": "tile-water",
};

const forestGroundBlendTiles = new Set(["T", "G", "^"]);

export const toVisual = (tile: string): VisualCell => {
	if (tileVisuals[tile]) return tileVisuals[tile];
	return { glyph: tile };
};

export const groundClassForTile = (
	tile: string,
	mapId?: MapId,
): string | undefined => {
	if (forestGroundBlendTiles.has(tile)) {
		return mapId === "forest" ? "tile-forest-grass" : "tile-grass";
	}
	return groundClassByTile[tile];
};

export const spriteTilesNeedingGround = new Set([
	"P",
	"+",
	"d",
	"w",
	"U",
	"V",
	"j",
	"l",
	"x",
	"h",
	"Y",
	"i",
	"'",
	GLYPH.seedling,
	GLYPH.shamrock,
	GLYPH.sheafOfRice,
	"1",
	"2",
	"3",
	"A",
	"D",
	"F",
	"I",
	"N",
	"E",
	"s",
	"f",
	"a",
	"$",
	"t",
	"c",
	"k",
	"b",
	"n",
	"m",
	"o",
	"p",
	"q",
	"r",
	"u",
	"v",
	"z",
	"T",
	"G",
	"C",
	"L",
	"O",
	"J",
	"X",
	"0",
	"4",
	"5",
	"7",
	"8",
	"9",
	"{",
	"}",
	"@",
	"%",
	"&",
	"?",
	"K",
	"e",
	"y",
	"!",
	"`",
	"\\",
	"|",
	GLYPH.newspaper,
	GLYPH.plateWithCutlery,
]);
