import type { MapId, VisualCell } from "../shared/types";

const tileVisuals: Record<string, VisualCell> = {
	"#": { glyph: "🧱" },
	",": { glyph: "", className: "tile-grass" },
	":": { glyph: "", className: "tile-sand" },
	";": { glyph: "", className: "tile-soil" },
	"=": { glyph: "", className: "tile-path" },
	")": { glyph: "", className: "tile-cave-path" },
	".": { glyph: "", className: "tile-floor" },
	"~": { glyph: "", className: "tile-water" },
	_: { glyph: "", className: "tile-gravel" },
	"^": { glyph: "", className: "tile-forest-grass" },
	"<": { glyph: "", className: "tile-cave-wall-dark" },
	">": { glyph: "", className: "tile-cave-wall-mid" },
	"*": { glyph: "", className: "tile-cave-wall-light" },
	"/": { glyph: "🪜", className: "tile-path" },
	T: { glyph: "🌲" },
	G: { glyph: "🌳" },
	C: { glyph: "🌵" },
	L: { glyph: "🪵" },
	O: { glyph: "🪨" },
	J: { glyph: "🌿" },
	X: { glyph: "🎁" },
	M: { glyph: "🍾", className: "tile-sand" },
	S: { glyph: "🐚", className: "tile-sand" },
	"0": { glyph: "😉" },
	"6": { glyph: "📦", className: "tile-grass" },
	"4": { glyph: "🥷" },
	"5": { glyph: "📦" },
	"7": { glyph: "🚁" },
	"8": { glyph: "🧍‍♂️" },
	"9": { glyph: "❤️" },
	Z: { glyph: "🧑‍⚕️", className: "tile-grass" },
	"{": { glyph: "🚜" },
	"}": { glyph: "🚜" },
	"@": { glyph: "🐈" },
	"%": { glyph: "🐈‍⬛" },
	"&": { glyph: "🐕" },
	"?": { glyph: "🐩" },
	K: { glyph: "🪸" },
	e: { glyph: "🐻" },
	y: { glyph: "🐍" },
	"!": { glyph: "💩" },
	"+": { glyph: "🚪" },
	d: { glyph: "🛏️" },
	w: { glyph: "👕" },
	U: { glyph: "🛁" },
	V: { glyph: "🛀" },
	j: { glyph: "🙂" },
	l: { glyph: "🪟" },
	x: { glyph: "🟫" },
	h: { glyph: "🪑" },
	B: { glyph: "", className: "tile-barn-wall" },
	H: { glyph: "🧱" },
	Y: { glyph: "🌱" },
	i: { glyph: "🌿" },
	"'": { glyph: "'" },
	s: { glyph: "🌱", className: "tile-shop-sign" },
	f: { glyph: "🧺", className: "tile-shop-sign" },
	a: { glyph: "🐄", className: "tile-shop-sign" },
	$: { glyph: "💰", className: "tile-shop-sign" },
	t: { glyph: "🧰", className: "tile-shop-sign" },
	c: { glyph: "👕", className: "tile-shop-sign" },
	k: { glyph: "☕", className: "tile-shop-sign" },
	n: { glyph: "🙂" },
	b: { glyph: "👷", className: "tile-floor" },
	m: { glyph: "😎" },
	o: { glyph: "🥸" },
	p: { glyph: "🤠" },
	q: { glyph: "⛵" },
	r: { glyph: "🛶" },
	u: { glyph: "🚤" },
	v: { glyph: "🛥️" },
	z: { glyph: "🚣‍♀️" },
	"[": { glyph: "⛲", className: "tile-grass" },
	"]": { glyph: "🌴", className: "tile-grass" },
	"`": { glyph: "\u{1F987}" },
	"\\": { glyph: "\u2709\uFE0F" },
	"|": { glyph: "🔥" },
	"1": { glyph: "🐄" },
	"2": { glyph: "🐑" },
	"3": { glyph: "🐔" },
	A: { glyph: "🦛" },
	D: { glyph: "🦄" },
	F: { glyph: "🦣" },
	I: { glyph: "🐌" },
	N: { glyph: "🦍" },
	E: { glyph: "🥚" },
	R: { glyph: "", className: "tile-roof-blue" },
	W: { glyph: "", className: "tile-roof-white" },
	g: { glyph: "", className: "tile-roof-gray" },
	Q: { glyph: "", className: "tile-roof-red" },
};

const groundClassByTile: Partial<Record<string, string>> = {
	",": "tile-grass",
	":": "tile-sand",
	";": "tile-soil-dry",
	"=": "tile-path",
	")": "tile-cave-path",
	_: "tile-gravel",
	".": "tile-floor",
	U: "tile-floor",
	x: "tile-floor",
	j: "tile-floor",
	h: "tile-floor",
	"~": "tile-water",
};

const forestGroundBlendTiles = new Set(["T", "G", "^"]);

export const toVisual = (tile: string): VisualCell => {
	if (tileVisuals[tile]) return tileVisuals[tile];
	return { glyph: tile };
};

export const groundClassForTile = (tile: string, mapId?: MapId): string | undefined => {
	if (forestGroundBlendTiles.has(tile)) {
		return mapId === "forest" ? "tile-forest-grass" : "tile-grass";
	}
	return groundClassByTile[tile];
};

export const spriteTilesNeedingGround = new Set([
	"P",
	"+",
	"d",
	"w",
	"U",
	"V",
	"j",
	"l",
	"x",
	"h",
	"Y",
	"i",
	"'",
	"\u{1F331}",
	"\u2618\uFE0F",
	"\u{1F33E}",
	"1",
	"2",
	"3",
	"A",
	"D",
	"F",
	"I",
	"N",
	"E",
	"s",
	"f",
	"a",
	"$",
	"t",
	"c",
	"k",
	"b",
	"n",
	"m",
	"o",
	"p",
	"q",
	"r",
	"u",
	"v",
	"z",
	"T",
	"G",
	"C",
	"L",
	"O",
	"J",
	"X",
	"0",
	"4",
	"5",
	"7",
	"8",
	"9",
	"{",
	"}",
	"@",
	"%",
	"&",
	"?",
	"K",
	"e",
	"y",
	"!",
	"`",
	"\\",
	"|",
]);





